import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { 
    padding: 30,
    backgroundColor: '#ffffff' 
  },
  title: { 
    fontSize: 24, 
    marginBottom: 20, 
    textAlign: 'center',
    color: '#3f51b5',
    fontWeight: 'bold'
  },
  section: { 
    margin: 10, 
    padding: 10, 
    borderBottom: '1px solid #dddddd' 
  },
  field: { 
    marginBottom: 8,
    fontSize: 12
  },
  label: { 
    fontWeight: 'bold',
    color: '#333333'
  },
  header: {
    fontSize: 16,
    marginBottom: 10,
    color: '#3f51b5',
    fontWeight: 'bold'
  },
  footer: { 
    marginTop: 30, 
    textAlign: 'center', 
    fontSize: 10,
    color: '#666666'
  },
  stage: {
    fontSize: 18,
    marginTop: 20,
    marginBottom: 10,
    textAlign: 'center',
    fontWeight: 'bold',
    padding: 10,
    backgroundColor: '#e8f5e9',
    color: '#2e7d32'
  }
});

export const LabReportPDF = ({ report, patient, doctor }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>Liver Cirrhosis Lab Report</Text>
      
      <View style={styles.section}>
        <Text style={styles.field}>
          <Text style={styles.label}>Patient: </Text>{patient?.name}
        </Text>
        <Text style={styles.field}>
          <Text style={styles.label}>Age/Sex: </Text>{report.age}/{report.sex}
        </Text>
        <Text style={styles.field}>
          <Text style={styles.label}>Doctor: </Text>{doctor?.name}
        </Text>
        <Text style={styles.field}>
          <Text style={styles.label}>Date: </Text>{new Date().toLocaleDateString()}
        </Text>
      </View>
      
      <View style={styles.section}>
        <Text style={styles.header}>Laboratory Findings</Text>
        {[
          ['Albumin', report.albumin, 'g/dL'],
          ['Bilirubin', report.bilirubin, 'mg/dL'],
          ['ALT', report.alt, 'U/L'],
          ['AST', report.ast, 'U/L'],
          ['ALP', report.alp, 'U/L'],
          ['INR', report.inr, ''],
          ['Platelets', report.platelets, 'K/uL'],
          ['Sodium', report.sodium, 'mEq/L'],
          ['Creatinine', report.creatinine, 'mg/dL']
        ].map(([label, value, unit]) => (
          <Text key={label} style={styles.field}>
            <Text style={styles.label}>{label}: </Text>{value} {unit}
          </Text>
        ))}
      </View>
      
      <View style={styles.section}>
        <Text style={styles.header}>Clinical Findings</Text>
        {[
          ['Ascites', report.ascites],
          ['Hepatomegaly', report.hepatomegaly],
          ['Spiders', report.spiders],
          ['Edema', report.edema]
        ].map(([label, value]) => (
          <Text key={label} style={styles.field}>
            <Text style={styles.label}>{label}: </Text>{value}
          </Text>
        ))}
      </View>
      
      <View style={styles.stage}>
        <Text>Predicted Cirrhosis Stage: {report.stage || 'Stage 1'}</Text>
      </View>
      
      <Text style={styles.footer}>
        This report is computer-generated and requires doctor validation.
        Generated by Liver Cirrhosis Portal on {new Date().toLocaleString()}
      </Text>
    </Page>
  </Document>
);

export default LabReportPDF;
